import Layout from '@/components/layout/Layout'
import CatalogPage from '@/components/templates/Catalog/CatalogPage'
import useRedirectByUserCheck from '@/hooks/useRedirectByUserCheck'
import { IQueryParams } from '@/types/Catalog.interface'
import { NextPage } from 'next'
import Head from 'next/head'

function Catalog({query}:{query:IQueryParams}) {
	
	return (
		<>
			<Head>
				<title>Sandjma | Каталог</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link
					rel='icon'
					type='image/svg'
					sizes='32x32'
					href='../public/img/logo.svg'
				/>
			</Head>
			<Layout>
				<main>
					<CatalogPage query={query}/>
					<div className='overlay'></div>
				</main>
			</Layout>
		</>
	)
}
export async function getServerSideProps(context:{query:IQueryParams}){
	return{
		props:{query:{...context.query}}
	}
}
export default Catalog
