import Layout from '@/components/layout/Layout'
import CatalogPage from '@/components/templates/Catalog/CatalogPage'
import useRedirectByUserCheck from '@/hooks/useRedirectByUserCheck'
import Head from 'next/head'

function Catalog() {
	const { shouldLoadContent } = useRedirectByUserCheck(false)
	return (
		<>
			<Head>
				<title>Sandjma  {shouldLoadContent ? '| Каталог' : ''}</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link
					rel='icon'
					type='image/svg'
					sizes='32x32'
					href='../public/img/logo.svg'
				/>
			</Head>
			<Layout>
				<main>
					<CatalogPage />
					<div className='overlay'></div>
				</main>
			</Layout>
		</>
	)
}

export default Catalog
