import AuthPage from '@/components/templates/Auth/AuthPage'
import useRedirectByUserCheck from '@/hooks/useRedirectByUserCheck'
import { NextPage } from 'next'
import Head from 'next/head'

const Dashboard: NextPage = () => {
	const { shouldLoadContent } = useRedirectByUserCheck(true)
	return (
		<>
			<Head>
				<title>Sandjma | {shouldLoadContent ? 'Авторизация' : ''}</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link
					rel='icon'
					type='image/svg'
					sizes='32x32'
					href='../public/img/logo.svg'
				/>
			</Head>

			{shouldLoadContent && <AuthPage />}
		</>
	)
}

export default Dashboard
