import AuthPage from '@/components/templates/Auth/AuthPage'
import Head from 'next/head'

function Home() {
	return (
		<>
			<Head>
				<title>Sandjma</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<AuthPage/>
		</>
	)
}

export default Home
