import AuthPage from '@/components/templates/Auth/AuthPage'
import Head from 'next/head'

function Home() {
	return (
		<>
			<Head>
				<title>Sandjma</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link
					rel='icon'
					type='image/svg'
					sizes='32x32'
					href='../public/img/logo.svg'
				/>
			</Head>
			<AuthPage />
		</>
	)
}

export default Home
