import Footer from '@/components/modules/Footer/Footer'
import Header from '@/components/modules/Header/Header'
import { NextPage } from 'next'
import Head from 'next/head'

const Dashboard: NextPage = () => {
	return (
		<>
			<Head>
				<title>Sandjma</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link
					rel='icon'
					type='image/svg'
					sizes='32x32'
					href='../public/img/logo.svg'
				/>
			</Head>
			<Header />
			<main>
				<h1>dashboard</h1>
				<div className='overlay'></div>
			</main>
			<Footer/>
		</>
	)
}

export default Dashboard
