import Layout from '@/components/layout/Layout'
import BGImage from '@/components/modules/DashboardPage/BGImage'
import DashboardPage from '@/components/templates/DashboardPage/DashboardPage'
import { NextPage } from 'next'
import Head from 'next/head'

const Dashboard: NextPage = () => {
	return (
		<>
			<Head>
				<title>Sandjma</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link
					rel='icon'
					type='image/svg'
					sizes='32x32'
					href='../public/img/logo.svg'
				/>
			</Head>
			<Layout>
				<main>
					
				</main>
				<BGImage />
				<DashboardPage/>
			</Layout>
		</>
	)
}

export default Dashboard
